import { useState } from "react"
import "./css/analyze-audio.css"
import axios from "axios"
import useAuth from "../helpers/useAuth";

export default function AnalyzeAudio(){

    const url = "http://localhost:3001/analyze-file"
    const [file, setFile] = useState();
    const [summary, setSummary] = useState("")
    const [transcript, setTranscript] = useState()
    const [showSummary, setShowSummary] = useState(true)

    const onFileUpload = async () => {
        try{
            console.log("onFileUpload");
		    const formData = new FormData();
		    formData.append(
			    "fileToAnalyze",
                //@ts-ignore
			    file,
		    );
		    console.log(file);
		    await axios.post(url, formData)
                            .then(response =>{
                                console.log("data:",response.data);
                                console.log("Summary:", response.data.summary);
                                console.log("Transcript:", response.data.transcript);
                                setSummary(response.data.summary)
                                setTranscript(response.data.transcript)
                            })
                            .catch(error =>{
                                console.error("Error getting summary", error)
                            })
        }catch (error){
            console.log("Error with file upload", error);
        }
	};

    const buttons = [
        {name: "Summary"},
        {name: "Transcript"},
    ]

    // const analyzeOptions = buttons.map((btn)=> <button className="analyze-options-btns" key={btn.name} onClick={()=>onAnalyze(btn.name)}>{btn.name}</button>)

    return (
        <div className="outer-div">
            {/* need to set the action still */}
            {/* <form encType="multipart/form-data" method="post" >
                <input id="fileupload" name="myfile" type="file" />
                <input type="submit" value="submit" id="submit" />
            </form> */}
            <div className="flex mt-10 items-center justify-center">
                <div className="w-full max-w-sm rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
                    <h2 className="mb-4 text-lg font-semibold text-slate-800">Upload File</h2>
                    <input
                        type="file"
                        name="fileToAnalyze"
                            className="block w-full cursor-pointer rounded-lg border border-slate-300 bg-slate-50 text-sm text-slate-700
                                        file:mr-4 file:rounded-md file:border-0 file:bg-blue-600 file:px-4 file:py-2
                                        file:text-sm file:font-semibold file:text-white hover:file:bg-blue-700"
                        //@ts-ignore
                        onChange={(e)=>setFile(e.target.files[0])}
                                        />
                        {/* <input type="submit" value="submit" id="submit" className="cursor-pointer rounded-lg border border-slate-300 bg-slate-50 text-sm text-slate-700"/> */}
                          <button 
                            className="mt-3 inline-block rounded-md bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700"
                            onClick={onFileUpload}
                            >
                                Submit
                            </button>
                </div>
            </div>
            <div id="analysis-container">
                <div id="btns-container">
                    <button onClick={(e)=>setShowSummary(true)} className="analyze-options-btns">Summary</button>
                    <button onClick={(e)=>setShowSummary(false)} className="analyze-options-btns">Transcript</button>
                    {/* <select className="analyze-options-select">
                        <option selected>English</option>
                        <option>Spanish</option>
                        <option>French</option>
                        <option>German</option>
                    </select> */}
                </div>
                {/* <label className="custom-checkbox"> */}
                    {/* <input id="calendar-checkbox" type="checkbox" /> */}
                    {/* <span className="checkmark"></span> */}
                    {/* Send tasks to calendar */}
                {/* </label> */}
                {/* the rows should be dynamic depending on the number of lines generated by the gemini output */}
                <textarea id="analysis-output" rows={10} cols={20} disabled value={showSummary ? summary : transcript}></textarea>
            </div>
        </div>
    )
}